/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import net.miginfocom.swing.MigLayout;
import swing.ScrollBar;

/**
 *
 * @author coora
 */
public class Chat_Body extends javax.swing.JPanel {

    /**
     * Creates new form Chat_Body
     */
    public Chat_Body() {
        initComponents();
        init();
        
        addItemLeft("I tried to use jTextPane1.setText(\"xxx xxxx xxx xxxxx xx xxx xxxx xxx etc...\"); but JTextPane does not word wrap it at all showing all the text in one line only instead. It would be interesting to support word wrap on jTextPane1 resized too...", "Duck");
        addItemLeft("Hello" +"gg" +"\ngg", "Meeso");
        
        addItemRight("I tried to use jTextPane1.setText(\"xxx xxxx xxx xxxxx xx xxx xxxx xxx etc...\"); but JTextPane does not word wrap it at all showing all the text in one line only instead. It would be interesting to support word wrap on jText too...");
        addItemRight("Hello" +"gg" +"\ngg");
        
        addItemLeft("Hello" +"gg" +"\ngg", "Guju");
        addItemRight("I tried to use jTextPane1.setText(\"xxx xxxx xxx xxxxx xx xxx xxxx xxx etc...\"); but JTextPane does not word wrap it at all showing all the text in one line only instead. It would be interesting to support word wrap on jTextPane1 resized too...");
        addItemRight("Hello" +"gg" +"\ngg");
        
        addItemLeft("Hello" +"gg" +"\ngg", "Jogo");
        addItemRight("I tried to use jTextPane1.setText(\"xxx xxxx xxx xxxxx xx xxx xxxx xxx etc...\"); but JTextPane does not word wrap it at all showing all the text in one line only instead. It would be interesting to support word wrap on jTextPane1 resized too...");
        addItemRight("Hello" +"gg" +"\ngg");
        addDate("10/02/2023");
        addItemLeft("Hello" +"gg" +"\ngg", "Gojo", new ImageIcon(getClass().getResource("/icon/testing/pro.png")));
        addItemRight("I tried to use jTextPane1.setText(\"xxx xxxx xxx xxxxx xx xxx xxxx xxx etc...\"); but JTextPane does not word wrap it at all showing all the text in one line only instead. It would be interesting to support word wrap on jTextPane1 resized too...", new ImageIcon(getClass().getResource("/icon/testing/gojo.png")));
        addItemRight("Hello" +"gg" +"\ngg");
        addDate("10/02/2023");
        addItemLeft("Hello" +"gg" +"\ngg", "Kenjaku");
        addItemRight("I tried to use jTextPane1.setText(\"xxx xxxx xxx xxxxx xx xxx xxxx xxx etc...\"); but JTextPane does not word wrap it at all showing all the text in one line only instead. It would be interesting to support word wrap on jTextPane1 resized too...");
        addItemRight("Hello" +"gg" +"\ngg", new ImageIcon(getClass().getResource("/icon/testing/gojo.png")));
        addDate("Today");
        addItemLeft("Hello" +"gg" +"\ngg", "Mahito", new ImageIcon(getClass().getResource("/icon/testing/pro.png")),  new ImageIcon(getClass().getResource("/icon/testing/gojo.png")));
        addItemLeft("" , "Mahito", new ImageIcon(getClass().getResource("/icon/testing/gojo.png")));

    
    }
    
    private void init(){
        body.setLayout(new MigLayout("fillx", "", "2[]2"));
        sp.setVerticalScrollBar(new ScrollBar());
        sp.getVerticalScrollBar().setBackground(Color.WHITE);
    }
    
    public void addItemLeft(String text, String user, Icon ...image){
        Chat_Left_With_Profile item = new Chat_Left_With_Profile();
        item.setText(text);
        item.setImage(image);
        item.setTime();
        item.setUserProfile(user);
        
        body.add(item, "wrap, w 100::80%");
        body.repaint();
        body.revalidate();
        
    }
    
    public void addItemRight(String text, Icon ...image){
        Chat_Right item = new Chat_Right();
        item.setText(text);
        item.setImage(image);
        body.add(item, "wrap, al right, w 100::80%");
        body.repaint();
        body.revalidate();
    }
    
    public void addDate(String date){
        Chat_Date item = new Chat_Date();
        item.setDate(date);
        body.add(item, "wrap, al center");
        body.repaint();
        body.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sp = new javax.swing.JScrollPane();
        body = new javax.swing.JPanel();

        sp.setBorder(null);
        sp.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        body.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        sp.setViewportView(body);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
